pub(crate) mod artwork;
pub(crate) mod connection;
pub(crate) mod integrations;
pub(crate) mod library;
pub(crate) mod models;
pub(crate) mod persistence;
pub(crate) mod playback_controls;
mod prelude;
pub(crate) mod queue;
pub(crate) mod shortcuts;
pub(crate) mod state;
pub mod styles;
pub(crate) mod tracklist;
pub(crate) mod widgets;
pub mod window;
